### ISSUE TITLE
Mapping in CL

### ISSUE THREAD

**Issue by edward-martyr** [ChiuMing-Neko/ChiuKongGothic#13]
In `CMap-Overwritten.csv`, there are some kanjis which remain unchanged, i.e., `音`, where it could have been changed to use `uni97F3uE0101-JP`. Is this intended?

**Comment by ChiuMing-Neko** [comment]
Intended.
[Referrence](https://github.com/ChiuMing-Neko/ChiuKongGothic/issues/6#issue-1063662742)

**Comment by edward-martyr** [comment]
So I read it as you're using 「表外漢字字体表」 as a primary reference for CL? I don't quite see why that document would be considered "classical". I totally like the idea of referring to that document; I just think you need a different name than CL.

**Comment by ChiuMing-Neko** [comment]
> I don't quite see why that document would be considered "classical". I just think you need a different name than CL.

The current full name of the "CL" version is "old-printing script version".
Even these glyph forms were not the most common form, but still can be found before the Chinese Character reformation after WW2. I don't see any reason for refusing to recognize them as one of the 'old-Ming typeface' glyph forms. 
![音-旧字体bot](https://user-images.githubusercontent.com/84143394/155998339-0e581d42-c333-4216-a1b2-db8e8e609dd2.png)
![寵-旧字体bot](https://user-images.githubusercontent.com/84143394/155999999-c254098b-2d14-497e-98d6-474b63ff13c0.png)
Source: [旧字体bot](https://twitter.com/kyujitai_bot)

![Newspaper](https://user-images.githubusercontent.com/84143394/156003026-3bea4b84-4112-4902-91c9-898053a7b9f4.png)

### Explanation
Firstly, I use the term 'default glyph' because it is just the default mapping of the version, using IVS could easily 'force' the client to show the desired glyph form regardless of using either CL version or MN version, or furthermore, if the font(generally Japanese font) that support Adobe-Japan 1 IVS collection, it could also show the corresponding glyph form. One of the reasons that I implement the IVS is because I am knowing that different people have different preferences on the glyph form that was chosen in 'old-Ming typeface' font. Unless you could give me a **'strong'** reason such as the corresponding glyph form is wrong, may create confusion, or is not suitable for use as a default glyph, and more importantly, the **reference source** is needed for all requests of changing the default glyph of CL version.

Second, there was a hard time for me before deciding to change them back to 'JP' or 'KR' default glyph form because the SHS itself generally follows the Hyogai Kanji guideline "いわゆる康煕字典体(so-called Kangxi dictionary glyph form)", several glyph forms may differ from the most common glyph form that used in old printing materials. Resulting in many of the 'actual Kangxi form' or 'most commonly used' glyph forms being included in neither Adobe Japan 1 nor Korean Name IVS collection that SHS currently fully supported. creating the glyph form inconsistency that is very easy to notice in commonly used characters.

Default glyph before Ver 1.220, which is largely based on the glyph form in [東京築地活版製造所の活字見本帖](http://www.asahi-net.or.jp/~sd5a-ucd/Tsukiji-5go-S11-Specimenbook.html), some of them were not changed due to no corresponding glyph form :
>「音」component:
![音](https://user-images.githubusercontent.com/84143394/155984501-0f225b5e-a68b-4db2-9fcc-c3fa64e648ef.png)

>「意」component:
![意](https://user-images.githubusercontent.com/84143394/155986518-1268f96f-8099-4027-89d0-cee0a76366be.png)

>「龍」component:
![龍](https://user-images.githubusercontent.com/84143394/155988105-515386ec-53a2-4cee-afff-94e8db19a019.png)

Since CL version 'should generally‘ follow the guideline of いわゆる康煕字典体, Kyuu-jitai as defined in Joyo-Kanji table or glyphwiki's 仮想J字形, which is meant not necessary to fully follow it. Therefore many of the components still differ such as 「契」、「曼」. I still have not decided yet should they remain the current mapping or switch to an alternate glyph form in the new version.

**Comment by edward-martyr** [comment]
That makes sense.
